name: h2048
version: 0.2.0.1
github: Javran/h2048
license: MIT
author: Javran Cheng
maintainer: Javran.C@gmail.com
description: >
  A haskell implementation of Game 2048,
  based on <https://github.com/gabrielecirulli/2048>.

category: Game

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base
- data-default
- lens
- MonadRandom
- mtl
- text

library:
  source-dirs: src

executables:
  h2048-simple:
    main: Simple.hs
    source-dirs: exe
    dependencies:
      - h2048
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Simple

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - h2048
      - hspec
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
