name: h2048
version: 0.4.0.0
github: Javran/h2048
license: MIT
author: Javran Cheng
maintainer: Javran.C@gmail.com
synopsis: An Implementation of Game 2048
description: >
  An Implementation of Game 2048,
  based on <https://github.com/gabrielecirulli/2048>.

category: Game

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base
- brick
- containers
- mtl
- text
- tf-random
- vector
- vector-algorithms
- vty

library:
  source-dirs: src

executables:
  h2048-simple:
    main: Simple.hs
    source-dirs: exe
    dependencies:
      - h2048
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Simple
  h2048-brick:
    main: BrickUi.hs
    source-dirs: exe
    dependencies:
      - h2048
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is BrickUi

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - h2048
      - hspec
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
